const json = (schema: Record<string, unknown>) => ({ "application/json": { schema } });
const response = (description: string, schema?: Record<string, unknown>) => ({ description, ...(schema ? { content: json(schema) } : {}) });
const ok = (name: string) => ({ "200": response("Operacion exitosa", { $ref: `#/components/schemas/${name}` }) });
const created = (name: string) => ({ "201": response("Recurso creado", { $ref: `#/components/schemas/${name}` }) });
const errors = { "400": response("Datos invalidos"), "401": response("No autenticado"), "403": response("Sin permisos"), "404": response("Recurso no encontrado"), "409": response("Conflicto") };
const idParameter = { name: "id", in: "path", required: true, schema: { type: "string" } };
const listParameters = (extra: Record<string, unknown>[] = []) => [
  { name: "page", in: "query", schema: { type: "integer", minimum: 1, default: 1 } },
  { name: "pageSize", in: "query", schema: { type: "integer", minimum: 1, maximum: 100, default: 20 } },
  ...extra,
];
const body = (schema: Record<string, unknown>) => ({ required: true, content: json(schema) });
const object = (required: string[], properties: Record<string, unknown>) => ({ type: "object", required, properties });
const id = { type: "string", minLength: 1 };

export const openApiDocument = {
  openapi: "3.0.3",
  info: { title: "LABMANAGE API", version: "1.0.0", description: "API de gestion de aulas, horarios, reservas, anotaciones y mantenimiento." },
  servers: [{ url: "/api" }],
  security: [{ bearerAuth: [] }],
  components: {
    securitySchemes: { bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "JWT" } },
    schemas: {
      User: { type: "object", properties: { id, name: { type: "string" }, email: { type: "string", format: "email" }, role: { enum: ["ENCARGADO", "AYUDANTE"] }, active: { type: "boolean" }, createdAt: { type: "string", format: "date-time" }, updatedAt: { type: "string", format: "date-time" } } },
      Classroom: { type: "object", properties: { id, code: { type: "string" }, name: { type: "string" }, type: { enum: ["LAB_COMPUTACION", "LAB_GENERAL", "AULA"] }, capacity: { type: ["integer", "null"] }, location: { type: ["string", "null"] }, status: { enum: ["ACTIVA", "INACTIVA", "EN_MANTENIMIENTO", "FUERA_SERVICIO"] } } },
      TimeSlot: { type: "object", properties: { id, label: { type: "string" }, startTime: { type: "string", example: "07:15" }, endTime: { type: "string", example: "08:45" }, order: { type: "integer" } } },
      Semester: { type: "object", properties: { id, name: { type: "string" }, startDate: { type: "string", format: "date-time" }, endDate: { type: "string", format: "date-time" }, workingDays: { type: "array", items: { type: "integer", minimum: 1, maximum: 6 } }, isActive: { type: "boolean" } } },
      Subject: { type: "object", properties: { id, code: { type: "string" }, name: { type: "string" }, active: { type: "boolean" } } },
      Teacher: { type: "object", properties: { id, code: { type: "string" }, name: { type: "string" }, email: { type: ["string", "null"], format: "email" }, active: { type: "boolean" } } },
      Schedule: { type: "object", properties: { id, classroomId: id, semesterId: id, subjectId: id, teacherId: { oneOf: [id, { type: "null" }] }, dayOfWeek: { type: "integer", minimum: 1, maximum: 6 }, timeSlotId: id, timeSlot: { $ref: "#/components/schemas/TimeSlot" }, note: { type: ["string", "null"] } } },
      Reservation: { type: "object", properties: { id, classroomId: id, semesterId: id, type: { enum: ["RECURRENTE", "PUNTUAL"] }, dayOfWeek: { oneOf: [{ type: "integer", minimum: 1, maximum: 6 }, { type: "null" }] }, date: { oneOf: [{ type: "string", format: "date-time" }, { type: "null" }] }, timeSlotId: id, status: { enum: ["PENDIENTE", "CONFIRMADA", "CANCELADA"] }, note: { type: ["string", "null"] } } },
      ClassroomState: { type: "object", properties: { classroomId: id, state: { enum: ["LIBRE", "OCUPADA", "MANTENIMIENTO"] }, reason: { type: "string" }, occupiedBy: { type: "object" } } },
      Annotation: { type: "object", properties: { id, classroomId: id, userId: id, date: { type: "string", format: "date-time" }, content: { type: "string" } } },
      Maintenance: { type: "object", properties: { id, classroomId: id, date: { type: "string", format: "date-time" }, reason: { type: "string" }, status: { enum: ["REPORTADO", "EN_PROGRESO", "COMPLETADO"] } } },
      AuthResponse: { type: "object", properties: { accessToken: { type: "string" }, refreshToken: { type: "string" }, user: { $ref: "#/components/schemas/User" } } },
      SessionSummary: { type: "object", properties: { id, createdAt: { type: "string", format: "date-time" }, expiresAt: { type: "string", format: "date-time" }, revokedAt: { oneOf: [{ type: "string", format: "date-time" }, { type: "null" }] }, userAgent: { oneOf: [{ type: "string" }, { type: "null" }] }, ip: { oneOf: [{ type: "string" }, { type: "null" }] }, current: { type: "boolean" } } },
      StatsOverview: { type: "object", properties: { totalClassrooms: { type: "integer" }, classroomsByType: { type: "array", items: { type: "object" } }, activeSemester: { oneOf: [{ $ref: "#/components/schemas/Semester" }, { type: "null" }] }, occupancyByClassroom: { type: "array", items: { type: "object" } }, pendingMaintenance: { type: "integer" }, reservationsByStatus: { type: "array", items: { type: "object" } } } },
    },
  },
  paths: {
    "/health": { get: { security: [], summary: "Estado y conectividad de la API", responses: { "200": response("Servicio disponible"), "503": response("Base de datos no disponible") } } },
    "/auth/login": { post: { security: [], summary: "Iniciar sesion (crea Session por dispositivo)", requestBody: body(object(["email", "password"], { email: { type: "string", format: "email", maxLength: 254 }, password: { type: "string", format: "password", minLength: 1, maxLength: 100 } })), responses: { ...ok("AuthResponse"), ...errors } } },
    "/auth/refresh": { post: { security: [], summary: "Rotar refresh token (body {token} o cookie lm_refresh)", requestBody: body(object(["token"], { token: { type: "string" } })), responses: { ...ok("AuthResponse"), ...errors } } },
    "/auth/logout": { post: { security: [], summary: "Revocar la sesion actual (Bearer o cookie lm_access)", responses: { "204": response("Sesion revocada") } } },
    "/auth/sessions": { get: { summary: "Listar sesiones del usuario autenticado", responses: { "200": response("Sesiones", { type: "array", items: { $ref: "#/components/schemas/SessionSummary" } }), ...errors } } },
    "/auth/sessions/{id}": { delete: { summary: "Revocar una sesion propia", parameters: [idParameter], responses: { "204": response("Sesion revocada"), ...errors } } },
    "/auth/me": { get: { summary: "Consultar perfil", responses: ok("User") }, patch: { summary: "Editar perfil", requestBody: body(object([], { name: { type: "string" }, email: { type: "string", format: "email" } })), responses: { ...ok("User"), ...errors } } },
    "/auth/me/password": { patch: { summary: "Cambiar contrasena", requestBody: body(object(["currentPassword", "newPassword"], { currentPassword: { type: "string", format: "password" }, newPassword: { type: "string", format: "password", minLength: 8 } })), responses: { ...ok("User"), ...errors } } },
    "/users": { get: { summary: "Listar usuarios", parameters: listParameters(), responses: { "200": response("Usuarios paginados") } }, post: { summary: "Crear usuario", requestBody: body({ $ref: "#/components/schemas/User" }), responses: { ...created("User"), ...errors } } },
    "/users/{id}": { get: { summary: "Obtener usuario", parameters: [idParameter], responses: { ...ok("User"), ...errors } }, patch: { summary: "Actualizar usuario", parameters: [idParameter], requestBody: body({ $ref: "#/components/schemas/User" }), responses: { ...ok("User"), ...errors } }, delete: { summary: "Desactivar usuario", parameters: [idParameter], responses: { "204": response("Usuario desactivado"), ...errors } } },
    "/classrooms": { get: { summary: "Listar aulas", parameters: listParameters([{ name: "q", in: "query", schema: { type: "string" } }, { name: "status", in: "query", schema: { type: "string" } }, { name: "includeInactive", in: "query", schema: { type: "boolean" } }]), responses: { "200": response("Aulas paginadas") } }, post: { summary: "Crear aula", requestBody: body({ $ref: "#/components/schemas/Classroom" }), responses: { ...created("Classroom"), ...errors } } },
    "/classrooms/{id}": { get: { summary: "Obtener aula", parameters: [idParameter], responses: { ...ok("Classroom"), ...errors } }, patch: { summary: "Actualizar aula", parameters: [idParameter], requestBody: body({ $ref: "#/components/schemas/Classroom" }), responses: { ...ok("Classroom"), ...errors } }, delete: { summary: "Desactivar aula", parameters: [idParameter], responses: { "204": response("Aula desactivada"), ...errors } } },
    "/classrooms/{id}/state": { get: { summary: "Estado del aula (LIBRE | OCUPADA | MANTENIMIENTO)", parameters: [idParameter, { name: "date", in: "query", schema: { type: "string", format: "date" } }, { name: "timeSlotId", in: "query", schema: id }], responses: { ...ok("ClassroomState"), ...errors } } },
    "/time-slots": { get: { summary: "Listar turnos", responses: { "200": response("Turnos", { type: "array", items: { $ref: "#/components/schemas/TimeSlot" } }) } }, post: { summary: "Crear turno", requestBody: body({ $ref: "#/components/schemas/TimeSlot" }), responses: { ...created("TimeSlot"), ...errors } } },
    "/time-slots/{id}": { get: { summary: "Obtener turno", parameters: [idParameter], responses: { ...ok("TimeSlot"), ...errors } }, patch: { summary: "Actualizar turno", parameters: [idParameter], requestBody: body({ $ref: "#/components/schemas/TimeSlot" }), responses: { ...ok("TimeSlot"), ...errors } }, delete: { summary: "Eliminar turno", parameters: [idParameter], responses: { "204": response("Turno eliminado"), ...errors } } },
    "/semesters": { get: { summary: "Listar semestres", parameters: listParameters(), responses: { "200": response("Semestres paginados") } }, post: { summary: "Crear semestre", requestBody: body({ $ref: "#/components/schemas/Semester" }), responses: { ...created("Semester"), ...errors } } },
    "/semesters/{id}": { get: { summary: "Obtener semestre", parameters: [idParameter], responses: { ...ok("Semester"), ...errors } }, patch: { summary: "Actualizar semestre", parameters: [idParameter], requestBody: body({ $ref: "#/components/schemas/Semester" }), responses: { ...ok("Semester"), ...errors } }, delete: { summary: "Eliminar semestre", parameters: [idParameter], responses: { "204": response("Semestre eliminado"), ...errors } } },
    "/semesters/{id}/activate": { post: { summary: "Activar semestre", parameters: [idParameter], responses: { ...ok("Semester"), ...errors } } },
    "/subjects": { get: { summary: "Listar materias", parameters: listParameters([{ name: "q", in: "query", schema: { type: "string" } }]), responses: { "200": response("Materias paginadas") } }, post: { summary: "Crear materia", requestBody: body({ $ref: "#/components/schemas/Subject" }), responses: { ...created("Subject"), ...errors } } },
    "/subjects/{id}": { get: { summary: "Obtener materia", parameters: [idParameter], responses: { ...ok("Subject"), ...errors } }, patch: { summary: "Actualizar materia", parameters: [idParameter], requestBody: body({ $ref: "#/components/schemas/Subject" }), responses: { ...ok("Subject"), ...errors } }, delete: { summary: "Desactivar materia", parameters: [idParameter], responses: { "204": response("Materia desactivada"), ...errors } } },
    "/teachers": { get: { summary: "Listar docentes", parameters: listParameters([{ name: "q", in: "query", schema: { type: "string" } }]), responses: { "200": response("Docentes paginados") } }, post: { summary: "Crear docente", requestBody: body({ $ref: "#/components/schemas/Teacher" }), responses: { ...created("Teacher"), ...errors } } },
    "/teachers/{id}": { get: { summary: "Obtener docente", parameters: [idParameter], responses: { ...ok("Teacher"), ...errors } }, patch: { summary: "Actualizar docente", parameters: [idParameter], requestBody: body({ $ref: "#/components/schemas/Teacher" }), responses: { ...ok("Teacher"), ...errors } }, delete: { summary: "Desactivar docente", parameters: [idParameter], responses: { "204": response("Docente desactivado"), ...errors } } },
    "/schedules": { get: { summary: "Consultar grilla de horarios", parameters: [{ name: "classroomId", in: "query", required: true, schema: id }, { name: "semesterId", in: "query", required: true, schema: id }], responses: { "200": response("Bloques academicos", { type: "array", items: { $ref: "#/components/schemas/Schedule" } }) } }, post: { summary: "Crear bloque academico (materia/docente en aula, dia y turno)", requestBody: body({ $ref: "#/components/schemas/Schedule" }), responses: { ...created("Schedule"), ...errors } } },
    "/schedules/{id}": { get: { summary: "Obtener bloque", parameters: [idParameter], responses: { ...ok("Schedule"), ...errors } }, patch: { summary: "Actualizar bloque", parameters: [idParameter], requestBody: body({ $ref: "#/components/schemas/Schedule" }), responses: { ...ok("Schedule"), ...errors } }, delete: { summary: "Eliminar bloque", parameters: [idParameter], responses: { "204": response("Bloque eliminado"), ...errors } } },
    "/reservations": { get: { summary: "Listar reservas (ayudantes solo ven las propias)", parameters: listParameters([{ name: "status", in: "query", schema: { type: "string" } }, { name: "classroomId", in: "query", schema: id }, { name: "semesterId", in: "query", schema: id }, { name: "type", in: "query", schema: { type: "string" } }]), responses: { "200": response("Reservas paginadas") } }, post: { summary: "Registrar reserva (queda PENDIENTE)", requestBody: body({ $ref: "#/components/schemas/Reservation" }), responses: { ...created("Reservation"), ...errors } } },
    "/reservations/{id}": { get: { summary: "Obtener reserva", parameters: [idParameter], responses: { ...ok("Reservation"), ...errors } }, patch: { summary: "Modificar reserva (dueño si esta PENDIENTE, o Encargado)", parameters: [idParameter], requestBody: body({ $ref: "#/components/schemas/Reservation" }), responses: { ...ok("Reservation"), ...errors } } },
    "/reservations/{id}/status": { patch: { summary: "Confirmar o cancelar reserva (Encargado; dueño puede cancelar su PENDIENTE)", parameters: [idParameter], responses: { ...ok("Reservation"), ...errors } } },
    "/availability/grid": { get: { summary: "Tabla semanal de disponibilidad (matriz dias x turnos por aula)", parameters: [{ name: "semesterId", in: "query", required: true, schema: id }, { name: "classroomId", in: "query", schema: id }, { name: "includePuntual", in: "query", schema: { type: "boolean" } }], responses: { ...ok("ClassroomState"), ...errors } } },
    "/annotations": { get: { summary: "Listar anotaciones", parameters: listParameters([{ name: "classroomId", in: "query", required: true, schema: id }, { name: "from", in: "query", schema: { type: "string", format: "date" } }, { name: "to", in: "query", schema: { type: "string", format: "date" } }]), responses: { "200": response("Anotaciones paginadas") } }, post: { summary: "Crear anotacion", requestBody: body({ $ref: "#/components/schemas/Annotation" }), responses: { ...created("Annotation"), ...errors } } },
    "/annotations/{id}": { get: { summary: "Obtener anotacion", parameters: [idParameter], responses: { ...ok("Annotation"), ...errors } }, patch: { summary: "Actualizar anotacion", parameters: [idParameter], requestBody: body({ $ref: "#/components/schemas/Annotation" }), responses: { ...ok("Annotation"), ...errors } }, delete: { summary: "Eliminar anotacion", parameters: [idParameter], responses: { "204": response("Anotacion eliminada"), ...errors } } },
    "/maintenance": { get: { summary: "Listar mantenimientos", parameters: listParameters([{ name: "classroomId", in: "query", schema: id }, { name: "status", in: "query", schema: { type: "string" } }]), responses: { "200": response("Mantenimientos paginados") } }, post: { summary: "Reportar mantenimiento", requestBody: body({ $ref: "#/components/schemas/Maintenance" }), responses: { ...created("Maintenance"), ...errors } } },
    "/maintenance/{id}": { get: { summary: "Obtener mantenimiento", parameters: [idParameter], responses: { ...ok("Maintenance"), ...errors } }, patch: { summary: "Actualizar estado", parameters: [idParameter], requestBody: body({ $ref: "#/components/schemas/Maintenance" }), responses: { ...ok("Maintenance"), ...errors } }, delete: { summary: "Eliminar mantenimiento", parameters: [idParameter], responses: { "204": response("Mantenimiento eliminado"), ...errors } } },
    "/stats/overview": { get: { summary: "Resumen estadistico", responses: { ...ok("StatsOverview"), ...errors } } },
  },
} as const;
